# Generated by Django 4.2.5 on 2023-10-15 05:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0007_trend'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostAttachments',
            new_name='PostAttachment',
        ),
    ]
