# Generated by Django 4.2.5 on 2023-11-10 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_category_gametitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='game_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='post.gametitle'),
        ),
    ]
