# Generated by Django 4.2.5 on 2023-11-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_post_game_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametitle',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
