# Generated by Django 4.2.5 on 2023-11-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_post_outside_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
