# Generated by Django 4.2.5 on 2023-11-20 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_post_post_url_post_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail_url',
        ),
    ]
