# Generated by Django 4.2.5 on 2023-11-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_remove_post_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('discussion', 'discussion'), ('connect', 'connect'), ('marketplace', 'marketplace'), ('tournament', 'tournament')], default='discussion', max_length=20),
        ),
    ]
