# Generated by Django 4.2.5 on 2023-11-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_rename_status_post_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattachment',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_attachments'),
        ),
    ]
