# Generated by Django 4.2.7 on 2023-11-24 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0019_postattachment_image_url_alter_postattachment_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="menu",
        ),
    ]
