# Generated by Django 4.2.7 on 2023-11-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0020_remove_post_menu"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menu", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="menu",
            field=models.CharField(
                choices=[
                    ("discussions", "Discussions"),
                    ("marketplace", "Marketplace"),
                    ("connect", "Connect"),
                    ("tournament", "Tournament"),
                    ("beta", "Beta Testing"),
                ],
                default="discussions",
                max_length=20,
            ),
        ),
    ]
