# Generated by Django 4.2.7 on 2023-11-24 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0021_menu_post_menu"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Menu",
        ),
    ]
