# Generated by Django 4.2.7 on 2023-11-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_delete_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='menu',
            field=models.CharField(choices=[('discussions', 'Discussions'), ('marketplace', 'Marketplace'), ('connect', 'Connect'), ('tournament', 'Tournament'), ('beta', 'Beta Testing')], default='Discussions', max_length=20),
        ),
    ]
