# Generated by Django 4.2.5 on 2023-10-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('new_friendrequest', 'New Friendrequest'), ('accepted_friendrequest', 'Accepted Friendrequest'), ('rejected_friendrequest', 'Rejected Friendrequest'), ('post_like', 'Post like'), ('post_comment', 'Post comment')], max_length=50),
        ),
    ]
