# Generated by Django 4.2.5 on 2023-11-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_pref_game_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(blank=True, to='account.category'),
        ),
        migrations.AlterField(
            model_name='pref_game_categories',
            name='categories',
            field=models.ManyToManyField(to='account.category'),
        ),
    ]
