# Generated by Django 4.2.5 on 2023-11-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_pref_game_categories_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='returned_game_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
