# Generated by Django 4.2.5 on 2023-11-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_returned_game_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='returned_game_title',
            new_name='pref_game_title',
        ),
    ]
