# Generated by Django 4.2.5 on 2023-11-11 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_returned_game_title_user_pref_game_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pref_game_title',
        ),
        migrations.AddField(
            model_name='user',
            name='pref_game_titles',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
