# Generated by Django 4.2.5 on 2023-11-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_user_pref_game_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pref_game_titles',
        ),
        migrations.AddField(
            model_name='user',
            name='pref_game_titles',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
