# Generated by Django 4.2.5 on 2023-11-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_user_pref_game_titles_user_pref_game_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pref_game_titles',
        ),
    ]
