# Generated by Django 4.2.5 on 2023-11-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_user_pref_game_titles_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pref_game_titles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
